version: "3.5"

services:
  api:
    image: devmentors/metigator.api
    container_name: api
    restart: always
    ports:
      - 5000:5000
    networks:
      - metigator

  customers-service:
    image: devmentors/metigator.services.customers
    container_name: customers-service
    restart: always
    ports:
      - 5001:5000 
    networks:
      - metigator

  identity-service:
    image: devmentors/metigator.services.identity
    container_name: identity-service
    restart: always
    ports:
      - 5002:5000
    networks:
      - metigator

  notifications-service:
    image: devmentors/metigator.services.notifications
    container_name: notifications-service
    restart: always
    ports:
      - 5003:5000
    networks:
      - metigator

  operations-service:
    image: devmentors/metigator.services.operations
    container_name: operations-service
    restart: always
    ports:
      - 5004:5000
    networks:
      - metigator

  orders-service:
    image: devmentors/metigator.services.orders
    container_name: orders-service
    restart: always
    ports:
      - 5005:5000
    networks:
      - metigator

  products-service:
    image: devmentors/metigator.services.products
    container_name: products-service
    restart: always
    ports:
      - 5006:5000
    networks:
      - metigator

  signalr-service:
    image: devmentors/metigator.services.signalr
    container_name: signalr-service
    restart: always
    ports:
      - 5007:5000
    networks:
      - metigator

networks:
  metigator:
    name: metigator-network
    external: true