version: "3.5"

services:
  api:
    image: devmentors/metigator.api
    ports:
      - '5000:5000'
    networks:
      - metigator
    environment:
      - 'CONSUL_ENABLED=false'
      - 'VAULT_ENABLED=false'

  customers-service:
    image: devmentors/metigator.services.customers
    ports:
      - '5001:5000'  
    networks:
      - metigator
    environment:
      - 'CONSUL_ENABLED=false'
      - 'VAULT_ENABLED=false'

  identity-service:
    image: devmentors/metigator.services.identity
    ports:
      - '5002:5000'
    networks:
      - metigator
    environment:
      - 'CONSUL_ENABLED=false'
      - 'VAULT_ENABLED=false'

  notifications-service:
    image: devmentors/metigator.services.notifications
    ports:
      - '5003:5000'
    networks:
      - metigator
    environment:
      - 'CONSUL_ENABLED=false'
      - 'VAULT_ENABLED=false'

  operations-service:
    image: devmentors/metigator.services.operations
    ports:
      - '5004:5000'
    networks:
      - metigator
    environment:
      - 'CONSUL_ENABLED=false'
      - 'VAULT_ENABLED=false'

  orders-service:
    image: devmentors/metigator.services.orders
    ports:
      - '5005:5000'
    networks:
      - metigator
    environment:
      - 'CONSUL_ENABLED=false'
      - 'VAULT_ENABLED=false'

  products-service:
    image: devmentors/metigator.services.products
    ports:
      - '5006:5000'
    networks:
      - metigator
    environment:
      - 'CONSUL_ENABLED=false'
      - 'VAULT_ENABLED=false'

  signalr-service:
    image: devmentors/metigator.services.signalr
    ports:
      - '5007:5000'
    networks:
      - metigator
    environment:
      - 'CONSUL_ENABLED=false'
      - 'VAULT_ENABLED=false'

networks:
  metigator:
    name: metigator-network
    external: true